name: Show OIDC JWT Token

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  get-jwt:
    runs-on: ubuntu-latest
    steps:
      - name: Get OIDC JWT and save to file
        run: |
          echo "Requesting GitHub OIDC token..."
          TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
              "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=github-actions" \
              | jq -r .value)

          echo "$TOKEN" > jwt_token.txt
          echo "JWT token saved to jwt_token.txt"
          echo "---- BEGIN JWT TOKEN ----"
          cat jwt_token.txt
          echo "---- END JWT TOKEN ----"
